---

# Create a host group: hydra_hosts from Inventory tool database
#
# Input Variables:
#
# API Credentials
# cred_token: <string>
#
# tool:
#   pool:   <int>
#   site:   <int>
#   tenant: <int>
#   status: <int>
#   limit:  <int>
- name: Create Hydra Based Host groups
  hosts: localhost
  gather_facts: no

  tasks:
      - name: Get the host from Inventory Tool 
        uri:
          url: "https://xyz/api/1.0/ci/search"
          method: POST
          body_format: json
          body:
              token: "{{api_token}}"
              parents_connection: "{{tool.pool}}"
              logical_site_id: "{{tool.site}}"
          timeout: 10
          validate_certs: no
        register: tool_output


      - name: Create host group
        add_host:
            name: "{{ item.hostname }}"
            groups: hydraaa_hosts
        with_items: "{{ tool_output.json.result }}"


