---
- import_playbook: hydra_inventory.yaml


- name: Update Linux OS
  hosts: hydra_hosts
  tasks:
    - name: Update Debian OS server
      apt:
        update-cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"

- name: Update Redhat family OS
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "Redhat"

- name: Update SUSE OS
  zypper:
    name: "*"
    state: latest
    type: patch
    update_cache: yes
  when: ansible_os_family == "Suse"

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required


- name: Reboot server
  shell: sync && shutdown -r now "Reboot initiated by Ansible for kernel updates"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists










